apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-ui.fullname" . }}
  labels:
    app: web-ui
    version: {{ .Values.image.tag }}
    circleci.com/component-name: "web-ui"
    circleci.com/version: {{ .Values.image.tag | quote }}
  annotations:
    circleci.com/project-id: {{ .Values.circleci.project_id | quote }}
    circleci.com/helm-revision-number: {{ .Release.Revision | quote }}
    circleci.com/pipeline-id: {{ .Values.circleci.pipelineId | quote }}
    circleci.com/workflow-id: {{ .Values.circleci.workflowId | quote }}
    circleci.com/job-number: {{ .Values.circleci.jobNumber | quote }}
    circleci.com/component-name: "web-ui"
    circleci.com/version: {{ .Values.image.tag | quote }}
    circleci.com/restore-version-enabled: "true"
    circleci.com/scale-component-enabled: "true"
    circleci.com/restart-component-enabled: "true"
    circleci.com/retry-release-enabled: "true"
    circleci.com/promote-release-enabled: "true"
    circleci.com/cancel-release-enabled: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "web-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        circleci.com/component-name: "web-ui"
        circleci.com/version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/instance: "web-ui"
        app.kubernetes.io/name: "web-ui"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web-ui.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
